# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 3
image:
  repository: us.icr.io/innovate_bank_shared/accounts
  tag: v1
  pullPolicy: Always
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
livenessProbe:
  initialDelaySeconds: 3000
  periodSeconds: 1000
service:
  name: Node
  type: NodePort
  servicePort: 3400
  serviceNodePort: 30121
hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 3
  metrics:
    cpu:
      targetAverageUtilization: 80
    memory:
      targetAverageUtilization: 80
services:
